spring:
  datasource:
    url: jdbc:mysql://123.207.88.92:3306/contract?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: lubao
    password: 84952139
  redis:
    host: 123.207.88.92 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 84952139 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
#  file:
#    path: /var/logs
  level:
    root: error
    com.macro.mall: error


# pdf保存的路径
uploadFilePath: /zy/contract/2021